### ISSUE TITLE
Support for streaming the audio

### ISSUE THREAD

**Issue by axchanda** [mozilla-services/deepspeech-server#2]
Hi @lissyx Can you add how we can stream audio into the DS server?

**Comment by lissyx** [comment]
> Hi @lissyx Can you add how we can stream audio into the DS server?

@axchanda  Can you give context ?

**Comment by axchanda** [comment]
Hi @lissyx It is like I have a stream of data, and it should infer it at the real-time. Something now that you pass file as a parameter to the server, but I need the servver, where I will be passing the stream of bytes to it and it should recognise it on real-time.

**Comment by lissyx** [comment]
> Hi @lissyx It is like I have a stream of data, and it should infer it at the real-time. Something now that you pass file as a parameter to the server, but I need the servver, where I will be passing the stream of bytes to it and it should recognise it on real-time.

I know what streaming is ... I'm asking your context ? Are your part of `mozila-services` ?

**Comment by axchanda** [comment]
@lissyx No, I'm not a part of mozilla-services.

**Comment by lissyx** [comment]
@axchanda i'm sorry, but this repository is really specific to some mozilla-services infrastructure.
