### ISSUE TITLE
Docker build cannot find version.json

### ISSUE THREAD

**Issue by kaiidams** [mozilla-services/deepspeech-server#6]
Env:

Ubuntu 18.04 amd64
CUDA 10.0
cuDNN 7.5.1
Docker CE 19.03.5

Run the command below

```
nvidia-docker build -f Dockerfile.gpu .
```

Fails with missing `version.json`.

```
Step 12/24 : RUN mkdir /app && chown ds:ds /app
 ---> Using cache
 ---> 38d0a02257a3
Step 13/24 : COPY --chown=ds:ds version.json /app/version.json
COPY failed: stat /var/lib/docker/tmp/docker-builder982803167/version.json: no such file or directory
```

**Comment by kaiidams** [comment]
Any JSON file should work. Probably need a predefined `version.json` or an example.

**Comment by lissyx** [comment]
> Any JSON file should work. Probably need a predefined `version.json` or an example.

This is required for deployment on the infra's, not for the general public use. See `.circleci/config.yml` on build.
